# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080


# ===============================
# DATABASE CONFIGURATION (Render)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# STATIC RESOURCES
# ===============================
spring.web.resources.static-locations=classpath:/static/


# ===============================
# SECURITY (DISABLE DEFAULT)
# ===============================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration



# yaha se application-local properties ko call jayegi aur system locally run karega
spring.profiles.active=local
