spring.datasource.url=jdbc:postgresql://dpg-d5lmmrv5r7bs73claa6g-a.oregon-postgres.render.com:5432/cafemanagementsystemdb?sslmode=require
spring.datasource.username=root
spring.datasource.password=psoC7CK4LG1npQDuGIhIKParb76k8coT
spring.datasource.driver-class-name=org.postgresql.Driver