spring.datasource.url=jdbc:postgresql://dpg-d51mmrv5r7bs73claa6g-a:5432/cafemanagementsystemdb
spring.datasource.username=root
spring.datasource.password=psoC7CK4LG1npQDuGIhIKParb76k8coT
spring.datasource.driver-class-name=org.postgresql.Driver
