spring.datasource.url=jdbc:postgresql://dpg-d4ugj8ur433s73djn3ig-a:5432/cafemanagementsystemdb
spring.datasource.username=root
spring.datasource.password=psoC7CK4LG1npQDuGIhIKParb76k8coT
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
