# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/CafeManagementSystem
spring.datasource.username=postgres
spring.datasource.password=Pass@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Disable default Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Optional (show SQL queries in console)
spring.jpa.show-sql=true
spring.web.resources.static-locations=classpath:/static/
spring.jpa.hibernate.ddl-auto=update

